### ISSUE TITLE
goroutine throws exception

### ISSUE THREAD

**Issue by cychiuae** [SkygearIO/skygear-server#250]
```
goroutine 2446102 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
github.com/skygeario/skygear-server/pkg/server/router.errorFromRecoveringPanic(0xb205c0, 0xc82000a0c0, 0x0, 0x0)
	/go/src/github.com/skygeario/skygear-server/pkg/server/router/errors.go:61 +0x122
github.com/skygeario/skygear-server/pkg/server/router.(*Router).ServeHTTP.func1(0xc821ddbd50, 0xd66581, 0x6, 0xc822b7b888)
	/go/src/github.com/skygeario/skygear-server/pkg/server/router/router.go:107 +0x6a
panic(0xb205c0, 0xc82000a0c0)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/skygeario/skygear-server/pkg/server/handler.(*RecordSaveHandler).Handle(0xc8200b84d0, 0xc820ee83c0, 0xc821ddbd50)
	/go/src/github.com/skygeario/skygear-server/pkg/server/handler/record.go:339 +0x177f
github.com/skygeario/skygear-server/pkg/server/router.(*Router).ServeHTTP(0xc820141b00, 0x7f55381b1ab0, 0xc8210bcea0, 0xc821447960)
	/go/src/github.com/skygeario/skygear-server/pkg/server/router/router.go:150 +0x649
net/http.(*ServeMux).ServeHTTP(0xc82013df20, 0x7f55381b1ab0, 0xc8210bcea0, 0xc821447960)
	/usr/local/go/src/net/http/server.go:1910 +0x17d
github.com/skygeario/skygear-server/pkg/server/router.(*CORSMiddleware).ServeHTTP(0xc82021fca0, 0x7f55381b1ab0, 0xc8210bcea0, 0xc821447960)
	/go/src/github.com/skygeario/skygear-server/pkg/server/router/cors.go:48 +0x563
net/http.serverHandler.ServeHTTP(0xc82001bb80, 0x7f55381b1ab0, 0xc8210bcea0, 0xc821447960)
	/usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc823968900)
	/usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2137 +0x44e
```

**Comment by cheungpat** [comment]
Need skygear-server version, and (if possible) request and response payload

**Comment by cychiuae** [comment]
@cheungpat 
The version is `0.19.1` and, sorry, I don't have the req and res payload

**Comment by cheungpat** [comment]
https://github.com/SkygearIO/skygear-server/blob/v0.19.1/pkg/server/handler/record.go#L339
