### ISSUE TITLE
[0.19.1] Goroutine panic

### ISSUE THREAD

**Issue by louischan-oursky** [SkygearIO/skygear-server#251]
(Describe the issue here)

- Skygear Server Date/Version: 0.19.1
- Application Platform:
- [ ] Is this a regression? Maybe
- [x] Attached logs, screenshots
```
goroutine 2033699 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
github.com/skygeario/skygear-server/pkg/server/router.errorFromRecoveringPanic(0xb205c0, 0xc82000a0c0, 0x0, 0x0)
	/go/src/github.com/skygeario/skygear-server/pkg/server/router/errors.go:61 +0x122
github.com/skygeario/skygear-server/pkg/server/router.(*Router).ServeHTTP.func1(0xc8223d33b0, 0xd66581, 0x6, 0xc824edd888)
	/go/src/github.com/skygeario/skygear-server/pkg/server/router/router.go:107 +0x6a
panic(0xb205c0, 0xc82000a0c0)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/skygeario/skygear-server/pkg/server/handler.(*RecordSaveHandler).Handle(0xc8201740b0, 0xc8223cc640, 0xc8223d33b0)
	/go/src/github.com/skygeario/skygear-server/pkg/server/handler/record.go:339 +0x177f
github.com/skygeario/skygear-server/pkg/server/router.(*Router).ServeHTTP(0xc820142760, 0x7f0b25673838, 0xc820f94270, 0xc824842460)
	/go/src/github.com/skygeario/skygear-server/pkg/server/router/router.go:150 +0x649
net/http.(*ServeMux).ServeHTTP(0xc820131b30, 0x7f0b25673838, 0xc820f94270, 0xc824842460)
	/usr/local/go/src/net/http/server.go:1910 +0x17d
github.com/skygeario/skygear-server/pkg/server/router.(*CORSMiddleware).ServeHTTP(0xc82022abc0, 0x7f0b25673838, 0xc820f94270, 0xc824842460)
	/go/src/github.com/skygeario/skygear-server/pkg/server/router/cors.go:48 +0x563
net/http.serverHandler.ServeHTTP(0xc82014da00, 0x7f0b25673838, 0xc820f94270, 0xc824842460)
	/usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc824c38a00)
	/usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2137 +0x44e
```

After upgrading to v0.19.1 from v0.14, our logging service starts this kind of log.

**Comment by rickmak** [comment]
Any example payload to trigger the panic?
